version: '3'
services:
  api:
    build:
      context: ./drop-mail-proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - next

  next:
    build:
      context: ./drop-mail-nb
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
